##################
# chroctl config #
##################
term="footclient"
editor="nvim"
mplayer="cmus"
volc=5
wallpath="$HOME/walls"
srcpath="/usr/local/bin/chroctl"

tweak_source() {
  notify-send "opening system editor in $srcpath.."
  sudoedit "$srcpath" && notify-send "success!" 
  # for confirmation reasons, this opens inside your current terminal
} # sudoedit uses your system editor 

tweak_config() {
  notify-send "opening $editor in $conf"
  "$term" -e "$editor" "$conf" &
}

open_editor() {
  notify-send "opening $editor.."
  "$term" -e "$editor" . & # this opens in your current path
} # change this if you use a gui editor

open_music() {
  notify-send "launch music player.."
  "$term" -e "$mplayer" &
}
