#!/bin/bash
# nct init


if [[ -f main.c || -f Makefile ]]; then
    echo "X_X: project already initialised, main.c and Makefile detected"
    exit 1
fi

cat << 'EOF' > main.c
#include <stdio.h>

int main() {

  printf("hello, world!\n");

  return 0;
}
EOF

cat << 'EOF' > Makefile
CC = clang
CFLAGS = -Wall -Wextra -O2

all: main

main: main.c
	@$(CC) $(CFLAGS) main.c -o main

clean:
	rm -f main
EOF

echo "^w^: nathan's c tool finished initialsing. happy coding!"
