#!/bin/bash

if [ -z "$1" ]; then
    echo "usage: nct <command>"
    exit 1
fi

SUBCOMMAND=$1

PLUGIN_NAME="nct-$SUBCOMMAND"

if command -v "$PLUGIN_NAME" >/dev/null 2>&1; then
    shift
    exec "$PLUGIN_NAME" "$@"
else
    echo "nct: '$SUBCOMMAND' doesnt exist"
    echo "try nct help, and check your .local/bin"
    exit 1
fi
